// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0JhpgkGr68ER0I8czYxoP_s2la_Penig',
    appId: '1:99083580527:web:4fae71bbc3ae2f72b5099a',
    messagingSenderId: '99083580527',
    projectId: 'whater-3d513',
    authDomain: 'whater-3d513.firebaseapp.com',
    storageBucket: 'whater-3d513.appspot.com',
    measurementId: 'G-FGHZ0BTNWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWoaeN5xtLrgg0tvtCF3KlDPfQOMjmtk',
    appId: '1:99083580527:android:8e5fe665017b2804b5099a',
    messagingSenderId: '99083580527',
    projectId: 'whater-3d513',
    storageBucket: 'whater-3d513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcjuHxD8O5waVS8pKNx-2FpKUfZKPtO4',
    appId: '1:99083580527:ios:3d48762861b61eb3b5099a',
    messagingSenderId: '99083580527',
    projectId: 'whater-3d513',
    storageBucket: 'whater-3d513.appspot.com',
    iosBundleId: 'com.example.theWater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAcjuHxD8O5waVS8pKNx-2FpKUfZKPtO4',
    appId: '1:99083580527:ios:ba41c1cf59f40c37b5099a',
    messagingSenderId: '99083580527',
    projectId: 'whater-3d513',
    storageBucket: 'whater-3d513.appspot.com',
    iosBundleId: 'com.example.theWater.RunnerTests',
  );
}
